name: project2
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v6
        env:
          SUPER_SECRET_TOKEN: ${{ secrets.SUPER_SECRET_TOKEN }}
