name: NodeJS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to?'
        required: true
        default: 'dev-1'
        type: choice
        options:
          - dev-1
          - dev-2
          - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the repository onto the runner
      - name: Checkout repository
        uses: actions/checkout@v6
  
      # Step 2: Install Node.js and configure dependency caching
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18' # Specify your required Node.js version

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              npm-cache-
  
      # Step 3: Clean install project dependencies
      - name: Install dependencies
        run: npm install
      # Step 4: Execute Build & test suite
      - name: Build
        run: npm run build
      
      - name: Run tests
        run: npm test

      - name: Artifact Build
        uses: actions/upload-artifact@v6
        with:
          name: artifact-1
          path: |
              package*

      - name: Deploy
        run: echo "Deploying to Production Server..."
