name: NodeJS

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the repository onto the runner
      - name: Checkout repository
        uses: actions/checkout@v6
  
      # Step 2: Install Node.js and configure dependency caching
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18' # Specify your required Node.js version
  
      # Step 3: Clean install project dependencies
      - name: Install dependencies
        run: npm install
      # Step 4: Execute Build & test suite
      - name: Build
        run: npm build
      
      - name: Run tests
        run: npm test

      - name: Deploy
        run: echo "Deploying to Production Server..."
